export type Task = {
    app_name: string,
    id: number,
    tid: number,
    name: string,
    color: string,
    kind: string,
    state: string,
    runtime: string,
    scheduled: string,
    idle: string,
    busy: string,
    location: string,
    created_at: string,
    starved: boolean,
    starved_since_ms: number,
    woken_at: string,
    scheduled_at: string,
};
